export const DEMO_TECHNICIAN = {
  name: 'Mohamed Ben Ali',
  email: 'mohamed.benali@tarcom.fr',
  id: 'TECH-23517560',
  phone: '+33 6 12 34 56 78',
  department: 'PLP Façade & Telecom',
  status: 'Disponible' as 'Disponible' | 'En intervention' | 'Hors ligne',
  currentAssignment: 'Intervention #23517560 - 15 Rue Exemple, Paris',
  stats: {
    totalInterventions: 1245,
    completed: 1050,
    pending: 120,
    nok: 75,
    successRate: '94%',
    avgDuration: '1h 45m',
  },
}

export const DEMO_INTERVENTIONS = [
  {
    reference: '23517560',
    type: 'PLP Façade',
    status: 'Terminé',
    technicianName: 'Mohamed Ben Ali',
    date: '07/08/2026',
    startTime: '08:00',
    endTime: '10:00',
    location: '15 Rue Exemple, Paris',
    result: 'OK',
    description: 'Pose et raccordement boîtier PLP Façade client 3ème étage. Signal optique optimal (-18 dBm).',
  },
  {
    reference: '23517561',
    type: 'Fibre Optique',
    status: 'En cours',
    technicianName: 'Mohamed Ben Ali',
    date: '07/08/2026',
    startTime: '10:30',
    endTime: '12:30',
    location: '42 Avenue des Champs-Élysées, Paris',
    result: 'En cours',
    description: 'Raccordement PTO abonné entreprise, soudure fibre monomode.',
  },
  {
    reference: '23517562',
    type: 'Maintenance Raccordement',
    status: 'Terminé',
    technicianName: 'Youssef Mansouri',
    date: '06/08/2026',
    startTime: '14:00',
    endTime: '16:00',
    location: '8 Rue de la Paix, Paris',
    result: 'OK',
    description: 'Remplacement connecteur SC/APC défectueux dans armoire de rue.',
  },
  {
    reference: '23517563',
    type: 'Dépannage Urgence',
    status: 'NOK',
    technicianName: 'Karim Said',
    date: '06/08/2026',
    startTime: '16:30',
    endTime: '18:00',
    location: '12 Boulevard Haussmann, Paris',
    result: 'NOK (Câble sectionné)',
    description: 'Câble principal sectionné par travaux de voirie tierce. Génie civil requis.',
  },
  {
    reference: '23517564',
    type: 'Audit Technique',
    status: 'Planifié',
    technicianName: 'Thomas Dubois',
    date: '08/08/2026',
    startTime: '09:00',
    endTime: '11:00',
    location: '25 Rue du Commerce, Paris',
    result: 'Planifié',
    description: 'Audit de faisabilité passage de câble colonne montante immeuble haussmannien.',
  },
  {
    reference: '23517565',
    type: 'PLP Façade',
    status: 'Terminé',
    technicianName: 'Sarah Martin',
    date: '05/08/2026',
    startTime: '08:30',
    endTime: '10:30',
    location: '10 Avenue Victor Hugo, Paris',
    result: 'OK',
    description: 'Installation façade neuve, passage goulotte de protection.',
  },
  {
    reference: '23517566',
    type: 'Maintenance Raccordement',
    status: 'Terminé',
    technicianName: 'Mohamed Ben Ali',
    date: '05/08/2026',
    startTime: '11:00',
    endTime: '13:00',
    location: '93 Rue de Rivoli, Paris',
    result: 'OK',
    description: 'Contrôle puissance réflectométrique et nettoyage pigtails.',
  },
]

export const DEMO_CHARTS = {
  dailyInterventions: [
    { day: 'Lun 03/08', ok: 42, nok: 3, pending: 5 },
    { day: 'Mar 04/08', ok: 48, nok: 2, pending: 4 },
    { day: 'Mer 05/08', ok: 55, nok: 4, pending: 6 },
    { day: 'Jeu 06/08', ok: 50, nok: 5, pending: 8 },
    { day: 'Ven 07/08', ok: 62, nok: 2, pending: 7 },
    { day: 'Sam 08/08', ok: 25, nok: 1, pending: 3 },
  ],
  technicianPerformance: [
    { name: 'Mohamed Ben Ali', interventions: 245, successRate: 96 },
    { name: 'Youssef Mansouri', interventions: 210, successRate: 94 },
    { name: 'Karim Said', interventions: 198, successRate: 92 },
    { name: 'Thomas Dubois', interventions: 185, successRate: 91 },
    { name: 'Sarah Martin', interventions: 212, successRate: 95 },
  ],
  statusDistribution: [
    { name: 'Completed (OK)', value: 1050, color: '#10b981' },
    { name: 'Pending', value: 120, color: '#f59e0b' },
    { name: 'NOK', value: 75, color: '#ef4444' },
  ],
  typeDistribution: [
    { type: 'PLP Façade', percentage: 45, count: 560 },
    { type: 'Fibre Optique', percentage: 30, count: 373 },
    { type: 'Maintenance Raccordement', percentage: 15, count: 187 },
    { type: 'Dépannage Urgence', percentage: 10, count: 125 },
  ],
}
